version: "3"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 5001:5000
    command: java -jar /threedollar-api.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    links:
      - "redis:redis"
    volumes:
      - ~/logs/api:/logs/api
  redis:
    image: redis
    command: redis-server --port 6379
    hostname: redis
    volumes:
      - ~/db/data:/data
