version: "3"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 5001:5000
    command: java -jar /threedollar-api.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "ADMIN_SERVER_URL=http://admin:4000"
    links:
      - "redis:redis"
      - "admin:admin"
    volumes:
      - ~/logs/api:/logs/api
  redis:
    image: redis
    command: redis-server --port 6379
    volumes:
      - ~/db/data:/data
  admin:
    image: ${ADMIN_IMAGE}:${TAG}
    ports:
      - 4001:4000
    command: java -jar /threedollar-admin.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    volumes:
      - ~/logs/admin:/logs/admin
